// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheSkyHomestay.Data.EF;

#nullable disable

namespace TheSkyHomestay.Data.Migrations
{
    [DbContext(typeof(TheSkyHomestayDbContext))]
    [Migration("20220928171029_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("372ea575-2536-4076-9bab-3e3138de495f"),
                            RoleId = new Guid("9e87b492-5343-4272-9a34-fa5de7cffb22")
                        },
                        new
                        {
                            UserId = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4"),
                            RoleId = new Guid("8f7579ee-4af9-4b71-9ada-7f792f76dc31")
                        },
                        new
                        {
                            UserId = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15"),
                            RoleId = new Guid("8f7579ee-4af9-4b71-9ada-7f792f76dc31")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens", (string)null);
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(3268));

                    b.Property<Guid>("TouristId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TouristId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3892),
                            TouristId = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4")
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3894),
                            TouristId = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15")
                        });
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(2456));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<Guid>("TouristId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(2552));

                    b.Property<int>("Vote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("TouristId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Phòng rất đẹp! Anh chủ rất dễ thương luôn!",
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3871),
                            IsDeleted = false,
                            RoomId = 1,
                            TouristId = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4"),
                            UpdatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3872),
                            Vote = 5
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Phòng rất đẹp! Anh chủ rất dễ thương luôn!",
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3874),
                            IsDeleted = false,
                            RoomId = 3,
                            TouristId = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15"),
                            UpdatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3875),
                            Vote = 5
                        });
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 171, DateTimeKind.Local).AddTicks(7650));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Stars")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 171, DateTimeKind.Local).AddTicks(7773));

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4533),
                            IsDeleted = false,
                            Name = "Hollywood",
                            Price = 500000m,
                            Stars = 5.0,
                            UpdatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4535)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4536),
                            IsDeleted = false,
                            Name = "Tokyo",
                            Price = 500000m,
                            Stars = 5.0,
                            UpdatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4537)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4538),
                            IsDeleted = false,
                            Name = "Berlin",
                            Price = 500000m,
                            Stars = 4.5,
                            UpdatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4538)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4539),
                            IsDeleted = false,
                            Name = "Paris",
                            Price = 800000m,
                            Stars = 5.0,
                            UpdatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4539)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4540),
                            IsDeleted = false,
                            Name = "California",
                            Price = 800000m,
                            Stars = 5.0,
                            UpdatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4540)
                        });
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.RoomBooking", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(66));

                    b.Property<DateTime>("CancelingTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckInDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 171, DateTimeKind.Local).AddTicks(9855));

                    b.Property<DateTime>("CheckOutDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 171, DateTimeKind.Local).AddTicks(9943));

                    b.Property<decimal>("Deposit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("IsCanceled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BillId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomBookings");

                    b.HasData(
                        new
                        {
                            BillId = 1,
                            RoomId = 1,
                            BookingTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3915),
                            CancelingTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInDate = new DateTime(2022, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2022, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deposit = 200000m,
                            IsCanceled = false,
                            Price = 500000m,
                            Total = 500000m
                        },
                        new
                        {
                            BillId = 1,
                            RoomId = 3,
                            BookingTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3917),
                            CancelingTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInDate = new DateTime(2022, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2022, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deposit = 200000m,
                            IsCanceled = false,
                            Price = 500000m,
                            Total = 500000m
                        },
                        new
                        {
                            BillId = 2,
                            RoomId = 4,
                            BookingTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3919),
                            CancelingTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInDate = new DateTime(2022, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2022, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deposit = 500000m,
                            IsCanceled = false,
                            Price = 800000m,
                            Total = 800000m
                        });
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.RoomCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 171, DateTimeKind.Local).AddTicks(8090));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 171, DateTimeKind.Local).AddTicks(8178));

                    b.HasKey("Id");

                    b.ToTable("RoomCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4651),
                            IsDeleted = false,
                            Name = "Phòng 1 giường",
                            UpdatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4652)
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4653),
                            IsDeleted = false,
                            Name = "Phòng 2 giường",
                            UpdatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4653)
                        });
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.RoomImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(2916));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(3012));

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3958),
                            Description = "Ảnh phòng 1",
                            IsDeleted = false,
                            Name = "phong1-1.jpg",
                            RoomId = 1,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3959),
                            Description = "Ảnh phòng 1",
                            IsDeleted = false,
                            Name = "phong1-2.jpg",
                            RoomId = 1,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3960),
                            Description = "Ảnh phòng 1",
                            IsDeleted = false,
                            Name = "phong1-3.jpg",
                            RoomId = 1,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3961),
                            Description = "Ảnh phòng 1",
                            IsDeleted = false,
                            Name = "phong2-1.jpg",
                            RoomId = 2,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3962),
                            Description = "Ảnh phòng 1",
                            IsDeleted = false,
                            Name = "phong2-1.jpg",
                            RoomId = 2,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 171, DateTimeKind.Local).AddTicks(8551));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 171, DateTimeKind.Local).AddTicks(8661));

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4666),
                            Description = "200.000/lượt/24h, xe được bao xăng chạy thoải mái",
                            IsDeleted = false,
                            Name = "Thuê xe máy",
                            Price = 200000m,
                            UpdatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4667)
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4668),
                            Description = "50.000/lượt/người, được hỗ trợ kính lặn biển, vợt bắt nhum",
                            IsDeleted = false,
                            Name = "Lặn nhum",
                            Price = 50000m,
                            UpdatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4668)
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4669),
                            Description = "50.000/lượt/người, hướng dẫn leo núi, hỗ trợ nước uống",
                            IsDeleted = false,
                            Name = "Chinh phục Ma Thiên Lãnh",
                            Price = 50000m,
                            UpdatedTime = new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(4669)
                        });
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.ServiceBooking", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("BookingTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 172, DateTimeKind.Local).AddTicks(1338));

                    b.Property<DateTime>("CancelingTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCanceled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BillId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceBookings");

                    b.HasData(
                        new
                        {
                            BillId = 1,
                            ServiceId = 1,
                            Amount = 1,
                            BookingTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3939),
                            CancelingTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCanceled = false,
                            Price = 200000m,
                            Total = 200000m
                        },
                        new
                        {
                            BillId = 1,
                            ServiceId = 2,
                            Amount = 2,
                            BookingTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3941),
                            CancelingTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCanceled = false,
                            Price = 50000m,
                            Total = 100000m
                        },
                        new
                        {
                            BillId = 2,
                            ServiceId = 1,
                            Amount = 2,
                            BookingTime = new DateTime(2022, 9, 29, 0, 10, 29, 176, DateTimeKind.Local).AddTicks(3942),
                            CancelingTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCanceled = false,
                            Price = 200000m,
                            Total = 400000m
                        });
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("default.png");

                    b.Property<string>("CINo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisteredTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 171, DateTimeKind.Local).AddTicks(9210));

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 29, 0, 10, 29, 171, DateTimeKind.Local).AddTicks(9339));

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4"),
                            AccessFailedCount = 0,
                            Avatar = "lam.jpg",
                            CINo = "333444555",
                            ConcurrencyStamp = "bb87e47d-be66-46ca-8cd4-e6c43578d68e",
                            Email = "lam@gmail.com",
                            EmailConfirmed = false,
                            IsBlocked = false,
                            LockoutEnabled = false,
                            Name = "Nguyễn Tùng Lâm",
                            Password = "AQAAAAEAACcQAAAAELTwqetns19JKaQTtfvxH1TtzhulQijlOWYB4JmxF5I0Vp3b49nSTyg7tqUyJ6sp1A==",
                            PhoneNumber = "0338307449",
                            PhoneNumberConfirmed = false,
                            RegisteredTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15"),
                            AccessFailedCount = 0,
                            Avatar = "an.jpg",
                            CINo = "444555666",
                            ConcurrencyStamp = "f4fa4814-79e4-4687-a51e-cd8793fb4143",
                            Email = "an@gmail.com",
                            EmailConfirmed = false,
                            IsBlocked = false,
                            LockoutEnabled = false,
                            Name = "Nguyễn Văn An",
                            Password = "AQAAAAEAACcQAAAAEFhwflc7VhluZxmYQtGzQ/R6Wpl+KmSbnzlH8SelxGeMpsTAiUuLMlSm44+EQC3E0Q==",
                            PhoneNumber = "0338307994",
                            PhoneNumberConfirmed = false,
                            RegisteredTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("372ea575-2536-4076-9bab-3e3138de495f"),
                            AccessFailedCount = 0,
                            Avatar = "admin.jpg",
                            CINo = "777888999",
                            ConcurrencyStamp = "e6935f51-835f-4f57-9d97-5d1c9e89589f",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            IsBlocked = false,
                            LockoutEnabled = false,
                            Name = "John",
                            Password = "AQAAAAEAACcQAAAAEJD7DTzxsIXn7Be2lA1oQ71kt6/I/6NjyFQKLgyp1v4udK5nrQ2sJu51fQADaTRd4Q==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            RegisteredTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e87b492-5343-4272-9a34-fa5de7cffb22"),
                            ConcurrencyStamp = "ba37df17-85ca-4bc1-aa39-56f8b42edcb1",
                            Description = "Administrator role",
                            Name = "admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = new Guid("8f7579ee-4af9-4b71-9ada-7f792f76dc31"),
                            ConcurrencyStamp = "c58b3bbe-5794-4ff4-9f7f-fbd86bc305a5",
                            Description = "Tourist role",
                            Name = "tourist",
                            NormalizedName = "tourist"
                        });
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.Bill", b =>
                {
                    b.HasOne("TheSkyHomestay.Data.Models.User", "Tourist")
                        .WithMany()
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.Feedback", b =>
                {
                    b.HasOne("TheSkyHomestay.Data.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSkyHomestay.Data.Models.User", "Tourist")
                        .WithMany()
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.Room", b =>
                {
                    b.HasOne("TheSkyHomestay.Data.Models.RoomCategory", "Category")
                        .WithMany("Rooms")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.RoomBooking", b =>
                {
                    b.HasOne("TheSkyHomestay.Data.Models.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSkyHomestay.Data.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.RoomImage", b =>
                {
                    b.HasOne("TheSkyHomestay.Data.Models.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.ServiceBooking", b =>
                {
                    b.HasOne("TheSkyHomestay.Data.Models.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSkyHomestay.Data.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.Room", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("TheSkyHomestay.Data.Models.RoomCategory", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
